name: pull request workflow
on: [pull_request]
jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: node setup
        uses: actions/setup-node@master
        with:
          node-version: '13.x'
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: npm test
        run: npm run test:ci
  initialize_and_validate:
    name: initialize and validate
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: terraform init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './infrastructure/terraform'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: terraform validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: './infrastructure/terraform'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: terraform plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './infrastructure/terraform'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
